# Generated by Django 5.2.6 on 2025-09-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marosim', '0003_service_slug_servicesubcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='servicecategory',
            unique_together={('event_type', 'name')},
        ),
    ]
