# Generated by Django 5.2.6 on 2025-09-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marosim', '0004_alter_servicecategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='services',
            field=models.ManyToManyField(related_name='events', to='marosim.servicesubcategory'),
        ),
    ]
