# Generated by Django 5.2.6 on 2025-09-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marosim', '0008_service_image1_service_image2_service_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
