# Generated by Django 5.2.6 on 2025-09-22 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marosim', '0009_service_latitude_service_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profil', 'verbose_name_plural': 'Profillar'},
        ),
    ]
