# Generated by Django 5.2.6 on 2025-09-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marosim', '0010_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='service_type',
            field=models.CharField(blank=True, choices=[('tadbir_joyi', 'Tadbir joyi'), ('ovqatlanish', 'Ovqatlanish'), ('kiyim_aksessuar', 'Kiyim-kechak va aksessuarlar'), ('foto_video', 'Foto va video'), ('musiqa', 'Musiqa va ko‘ngilochar dastur'), ('dekoratsiya', 'Dekoratsiya va gulchambar'), ('transport', 'Transport va mehmonlar qulayligi'), ('boshqa', 'Boshqa xizmatlar')], max_length=50, null=True),
        ),
    ]
