# Generated by Django 5.2.6 on 2025-09-16 05:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Telefon raqamni to‘g‘ri kiriting.', regex='^\\+?\\d{9,15}$')])),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_provider', models.BooleanField(default=False)),
                ('service_type', models.CharField(blank=True, choices=[('sanatkor', 'San’atkor'), ('raqqosa', 'Raqqosa'), ('gulchi', 'Gulchi'), ('mashina', 'Mashina ijarasi'), ('other', 'Boshqa')], max_length=50, null=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('price_range', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
